steps:
  # 1. Build & Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/backend:latest', './apps/backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/backend:latest']

  # 2. Build & Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/frontend:latest', './apps/frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/frontend:latest']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scholacbt-api'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/backend:latest'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '[YOUR_CLOUD_SQL_CONNECTION_NAME]' # Ganti dengan Connection Name dari Console SQL

  # 4. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scholacbt-web'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/scholacbt-repo/frontend:latest'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
